#!/bin/bash

# Description: Link dotfiles to home directory

ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf

# mkdir -p ~/.config
# ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml


echo "# ================"
echo "# Dotfiles linked!"
echo "# ================"

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/install_manual.sh)"
