# Binding a key to reload .tmux.conf
unbind r
bind r source-file ~/.tmux.conf \; display "Configuration loaded !"

# Start window numbering at 1 (not 0)
#set -g base-index 1
#setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

# Increase history limit
set -g history-limit 10000

# 256 color support
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# Vi key binding
set -g status-keys vi
set -g mode-keys vi

# Copy selected text to tmux and, when supported, the system clipboard
set -s set-clipboard on

# In vi copy mode: press y to copy and exit
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# For WSL
#bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"

# Makes tmux monitor each window for activity. When output appears in an inactive window, tmux can mark that window in the status bar.
set -g monitor-activity on
set -g visual-activity on
